# ===============================
# PostgreSQL Database Configuration
# ===============================

spring.datasource.url=jdbc:postgresql://dpg-d9d1sg58nd3s73cfa780-a.singapore-postgres.render.com:5432/flight_book_db
spring.datasource.username=flight
spring.datasource.password=znp3EzT5Gt3WDyCTIPFDmad2PgTOEyru
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate Configuration
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# Server Configuration
# ===============================

server.port=8080