spring.application.name=booking
server.port=8080

# MySQL Configuration (Default - Autocreates database if not exists)
spring.datasource.url=jdbc:mysql://localhost:3306/flight_book_db?createDatabaseIfNotExist=true
spring.datasource.username=flight
spring.datasource.password=flight
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Configuration (Uncomment to use in-memory database)
# spring.datasource.url=jdbc:h2:mem:flightdb;DB_CLOSE_DELAY=-1
# spring.datasource.driver-class-name=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.jpa.hibernate.ddl-auto=update

